import {
  SWIPE_THRESHOLD,
  SWIPE_MOVE_MIN,
  SWIPE_COOLDOWN,
  SWIPE_MAX_DURATION,
  SWIPE_MIN_VELOCITY,
} from '../configs/constants.js';

/** Minimum ms after a fired swipe before a NEW touchstart is accepted (secondary guard). */
const POST_SWIPE_GUARD_MS = 350;

/**
 * Handles keyboard and swipe/pointer input, translating them into direction
 * callbacks for the game grid.
 *
 * Touch listeners are registered on `window` but only act on touches that
 * start outside interactive UI (buttons, modals, scrollable containers).
 * When a touch starts on UI, the manager steps aside entirely — no
 * `preventDefault`, no swipe tracking — so native scroll, button taps, and
 * modal interactions work naturally on mobile.
 *
 * Ghost-touch immunity: the only reliable, timing-independent way to
 * distinguish a real human swipe from a synthetic ghost event (generated by
 * Android WebView / Capacitor after every touch) is physical movement.
 * Real fingers always produce touchmove events. Ghost events are bare
 * touchstart+touchend pairs with no touchmove in between.
 * → the `#hasMoved` flag is the primary ghost filter and is immune to any
 *   timing skew, async JS lag, or platform timeStamp quirks.
 *
 * Secondary defences (defence in depth):
 * - `#activeTouchId`: only the exact finger that began the gesture can end it.
 * - `#swipeFired`: one move per gesture, regardless of how many touchend events fire.
 * - POST_SWIPE_GUARD_MS: discard any touchstart within 220ms of a fired swipe.
 * - Timing uses `e.timeStamp` (event-creation time, immune to JS processing lag).
 */
export class InputManager {
  /** @type {Phaser.Scene} */
  #scene;

  /** @type {number} */
  #pointerStartX = 0;

  /** @type {number} */
  #pointerStartY = 0;

  /**
   * `e.timeStamp` of the touchstart that began the current gesture.
   * @type {number}
   */
  #pointerStartTime = 0;

  /**
   * `e.timeStamp` of the last touchend that successfully fired a swipe.
   * @type {number}
   */
  #lastSwipeTime = 0;

  /** @type {boolean} True when the current touch started on an interactive element */
  #touchOnUI = false;

  /** @type {boolean} True once the current touch gesture has fired a swipe — prevents
   *  duplicate moves from a single physical swipe. Reset on the next touchstart. */
  #swipeFired = false;

  /**
   * True if at least one touchmove has fired during the current gesture.
   * Ghost events synthesised by Android WebView never generate touchmove.
   * Real human swipes always do, even for fast flicks (the finger physically moves).
   * This is the primary and most reliable ghost-swipe filter.
   * @type {boolean}
   */
  #hasMoved = false;

  /**
   * Identifier of the touch point that started the current gesture.
   * Only the matching changedTouch in touchend/touchcancel is processed.
   * @type {number | null}
   */
  #activeTouchId = null;

  /** @type {(direction: 'up'|'down'|'left'|'right') => void} */
  #onDirection;

  /** @type {() => void} */
  #onMenu;

  /** @type {() => boolean} */
  #isBlocked;

  /**
   * @param {Phaser.Scene} scene
   * @param {{
   *   onDirection: (direction: 'up'|'down'|'left'|'right') => void,
   *   onMenu: () => void,
   *   isBlocked: () => boolean,
   * }} callbacks
   */
  constructor(scene, { onDirection, onMenu, isBlocked }) {
    this.#scene = scene;
    this.#onDirection = onDirection;
    this.#onMenu = onMenu;
    this.#isBlocked = isBlocked;
  }

  /** Register keyboard and touch listeners. */
  bind() {
    this.#scene.input.keyboard.on('keydown', this.#handleKey, this);
    window.addEventListener('touchstart', this.#onTouchStart, { passive: false });
    window.addEventListener('touchmove', this.#onTouchMove, { passive: false });
    window.addEventListener('touchend', this.#onTouchEnd, { passive: false });
    window.addEventListener('touchcancel', this.#onTouchCancel, { passive: true });
  }

  /**
   * Returns true if the touch target is an interactive UI element that should
   * keep its native behaviour (buttons, modals, scrollable containers).
   * @param {HTMLElement} el
   * @returns {boolean}
   */
  #isInteractiveTarget(el) {
    return !!el.closest(
      'button, a, .fm-btn, .fm-modal-overlay, .fm-menu-btn, .fm-mode-badge, ' +
        '.fm-clickable, .fm-enemy-area, [data-action]',
    );
  }

  /** @param {Phaser.Input.Keyboard.Key} event */
  #handleKey = (event) => {
    if (this.#isBlocked()) return;

    /** @type {'up' | 'down' | 'left' | 'right' | null} */
    let direction = null;
    switch (event.code) {
      case 'ArrowUp':
      case 'KeyW':
        direction = 'up';
        break;
      case 'ArrowDown':
      case 'KeyS':
        direction = 'down';
        break;
      case 'ArrowLeft':
      case 'KeyA':
        direction = 'left';
        break;
      case 'ArrowRight':
      case 'KeyD':
        direction = 'right';
        break;
      case 'Escape':
        this.#onMenu();
        return;
    }
    if (direction) {
      event.preventDefault?.();
      this.#onDirection(direction);
    }
  };

  /** @param {TouchEvent} e */
  #onTouchStart = (e) => {
    if (e.touches.length !== 1) {
      // Multi-touch: fully invalidate the current gesture so that neither the
      // pending touchend NOR any future stale event can fire a move.
      this.#activeTouchId = null;
      this.#swipeFired = true; // blocks the touchend of the current gesture
      return;
    }

    const target = /** @type {HTMLElement} */ (e.target);

    // If the touch started on an interactive element, let the browser handle it
    // natively (buttons, modals with scroll, etc.) — no preventDefault, no tracking.
    if (this.#isInteractiveTarget(target)) {
      this.#touchOnUI = true;
      return;
    }

    // Secondary guard: discard any touchstart within POST_SWIPE_GUARD_MS of a
    // fired swipe. Catches ghost starts before they can even open a gesture window.
    const startTs = e.timeStamp || performance.now();
    if (startTs - this.#lastSwipeTime < POST_SWIPE_GUARD_MS) {
      this.#touchOnUI = true; // silently ignore — no tracking
      return;
    }

    this.#touchOnUI = false;
    this.#swipeFired = false;
    this.#hasMoved = false; // reset — requires physical movement to fire
    this.#activeTouchId = e.touches[0].identifier;
    // Prevent default within the game zone to avoid 300 ms tap delay,
    // text selection, and browser scroll during swipes.
    e.preventDefault();
    this.#pointerStartX = e.touches[0].clientX;
    this.#pointerStartY = e.touches[0].clientY;
    this.#pointerStartTime = startTs;
  };

  /** @param {TouchEvent} e */
  #onTouchMove = (e) => {
    // Only suppress scroll/zoom when the touch is a game swipe, not on UI.
    if (this.#touchOnUI) return;
    e.preventDefault();

    // Already confirmed as real movement — nothing more to track.
    if (this.#hasMoved) return;
    if (this.#activeTouchId === null) return;

    const touch = [...e.changedTouches].find((t) => t.identifier === this.#activeTouchId);
    if (!touch) return;

    // Require real physical displacement (≥ SWIPE_MOVE_MIN px) before
    // marking the gesture as genuine. Ghost/synthetic touchmove events
    // report zero or near-zero displacement — this filter catches them.
    const dx = touch.clientX - this.#pointerStartX;
    const dy = touch.clientY - this.#pointerStartY;
    if (dx * dx + dy * dy >= SWIPE_MOVE_MIN * SWIPE_MOVE_MIN) {
      this.#hasMoved = true;
    }
  };

  /** @param {TouchEvent} e */
  #onTouchEnd = (e) => {
    if (this.#touchOnUI) {
      this.#touchOnUI = false;
      return;
    }

    e.preventDefault();
    if (this.#swipeFired) return;
    if (this.#isBlocked()) return;

    // Only honour the specific finger that started this gesture.
    // Never fall back to changedTouches[0]: if #activeTouchId is null it means
    // the gesture was invalidated (multi-touch, cancel, or post-swipe guard)
    // and no orphaned touchend should be able to trigger a move.
    if (this.#activeTouchId === null) return;
    const touch = [...e.changedTouches].find((t) => t.identifier === this.#activeTouchId);
    if (!touch) return;

    // Gesture complete — clear active id so a future spurious touchend is ignored
    this.#activeTouchId = null;

    // PRIMARY GHOST FILTER: require real physical movement.
    // Synthetic ghost events from Android WebView never produce touchmove,
    // so #hasMoved stays false and the gesture is silently dropped.
    if (!this.#hasMoved) return;

    // Use e.timeStamp (event-creation time) — immune to JS processing lag.
    const now = e.timeStamp || performance.now();

    // Enforce cooldown between accepted moves
    if (now - this.#lastSwipeTime < SWIPE_COOLDOWN) return;

    // Reject swipes that took too long (finger resting then lifting)
    const duration = now - this.#pointerStartTime;
    if (duration > SWIPE_MAX_DURATION) return;

    const dx = touch.clientX - this.#pointerStartX;
    const dy = touch.clientY - this.#pointerStartY;
    const absDx = Math.abs(dx);
    const absDy = Math.abs(dy);
    const dist = Math.max(absDx, absDy);
    if (dist < SWIPE_THRESHOLD) return;

    // Reject slow accidental drags (finger drifting without intent)
    if (duration > 0 && dist / duration < SWIPE_MIN_VELOCITY) return;

    /** @type {'up' | 'down' | 'left' | 'right'} */
    const direction = absDx > absDy ? (dx > 0 ? 'right' : 'left') : dy > 0 ? 'down' : 'up';
    this.#lastSwipeTime = now;
    this.#swipeFired = true;
    this.#onDirection(direction);
  };

  /**
   * Browser cancelled the touch (e.g. notification, gesture conflict).
   * Reset gesture state so the next touchstart begins cleanly.
   * @param {TouchEvent} e
   */
  #onTouchCancel = (e) => {
    if (this.#touchOnUI) {
      this.#touchOnUI = false;
      return;
    }
    const cancelled = [...e.changedTouches].find((t) => t.identifier === this.#activeTouchId);
    if (cancelled) {
      this.#activeTouchId = null;
      this.#swipeFired = false;
      this.#hasMoved = false;
    }
  };

  /** Cleanup listeners. */
  shutdown() {
    this.#scene.input.keyboard?.off('keydown', this.#handleKey, this);
    window.removeEventListener('touchstart', this.#onTouchStart);
    window.removeEventListener('touchmove', this.#onTouchMove);
    window.removeEventListener('touchend', this.#onTouchEnd);
    window.removeEventListener('touchcancel', this.#onTouchCancel);
  }
}
